<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE peliculas [
  <!ELEMENT agendas (titulo, director, a単o)>
  <!ELEMENT titulo (#PCDATA)>
  <!ELEMENT director (nombre, apellido)>
  <!ELEMENT a単o (#PCDATA)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT apellido (#PCDATA)>
]>
<peliculas>
    <titulo>Shutter Island</titulo>
    <director>
      <nombre>Martin</nombre>
      <apellido>Scorsese</apellido>
    </director>
    <a単o>2010</a単o>
</peliculas>
